---
version: '3.8'
services:
  localstack:
    image: localstack/localstack:4.3.0
    container_name: multi_tenant_deployment_aws_infra
    hostname: localstack
    environment:
      USER: localstack
    volumes:
      - localstack-volume:/var/lib/localstack
    ports:
      - "127.0.0.1:4510-4560:4510-4560"
      - "127.0.0.1:4566:4566"
    networks:
      - localstack-tf-nw

  setup-deployment-localstack-tf:
    build:
      context: .
      dockerfile: Dockerfile
    image: setup-localstack-tf:1.0
    container_name: setup-localstack-tf
    working_dir: /terraform
    depends_on:
      - localstack
    environment:
      - TF_IN_AUTOMATION=true
    networks:
      - localstack-tf-nw

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_BROKER_ID=0
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CLIENT_USERS=admin
      - KAFKA_CLIENT_PASSWORDS=admin-secret

networks:
  localstack-tf-nw:
    driver: bridge

volumes:
  localstack-volume:
